name: Build template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  execute_build_and_upload_artifact:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.29.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint:fix

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Run Tests
        run: pnpm test --run

      - name: Build application
        run: pnpm build --preset cloudflare_pages
        env:
          NUXT_PUBLIC_SITE_LGU_TYPE: ${{ vars.NUXT_PUBLIC_SITE_LGU_TYPE }}
          NUXT_PUBLIC_SITE_MUNICIPALITY: ${{ vars.NUXT_PUBLIC_SITE_MUNICIPALITY }}
          NUXT_PUBLIC_SITE_PROVINCE: ${{ vars.NUXT_PUBLIC_SITE_PROVINCE }}
          NUXT_PUBLIC_SITE_REGION: ${{ vars.NUXT_PUBLIC_SITE_REGION }}
          NUXT_PUBLIC_SITE_SITE_ID: ${{ vars.NUXT_PUBLIC_SITE_SITE_ID }}
          NUXT_PUBLIC_SITE_DOMAIN: ${{ vars.NUXT_PUBLIC_SITE_DOMAIN }}
          NUXT_PUBLIC_SITE_TAGLINE: ${{ vars.NUXT_PUBLIC_SITE_TAGLINE }}
          NUXT_PUBLIC_SITE_THEME_COLOR: ${{ vars.NUXT_PUBLIC_SITE_THEME_COLOR }}
          NUXT_PUBLIC_SITE_OFFICIAL_WEBSITE: ${{ vars.NUXT_PUBLIC_SITE_OFFICIAL_WEBSITE }}}

      - name: (${{ inputs.environment }}) Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: betterbinangonan-build-artifact
          path: ./dist
