name: Build & Deploy to Github pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.29.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint:fix

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Run Tests
        run: pnpm test --run

      - name: Build application
        run: pnpm build --preset github_pages

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./.output/public

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5
