name: Build & Deploy to Github pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        required: true
        type: choice
        default: Production
        options:
          - Development
          - Production

permissions:
  pages: write
  id-token: write
  pull-requests: write
  contents: write

concurrency:
  group: preview-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.29.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint:fix

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Run Tests
        run: pnpm test --run

      - name: Build application
        run: pnpm build --preset github_pages

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deployDev.outputs.pages-url || steps.deployProd.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v3

      - if: github.event.inputs.environment == 'Development'
        name: Deploy to Development
        id: deployDev
        uses: rajyan/preview-pages@v1
        with:
          source-dir: .
      - if: github.event.inputs.environment == 'Production'
        name: Deploy to Production
        id: deployProd
        uses: actions/deploy-pages@v4
